создание калькулятора
js-tasks-ru/vue-20241213_kira-ismailova pull request #6
Opened 2024-12-27 19:57 UTC by KiraIsmailova

2024-12-27 19:57 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-27 20:39 UTC, ShGKme requested changes

2024-12-27 20:39 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +    watch([firstNum, secondNum, operator], calc);
Здесь через отслеживание вручную реализовано вычисление `result` при изменении любой из зависимостей вычисления. Фактически реализовано вычисляемое свойство, но вручную. Такие свойства нужно реализовывать именно как вычисляемое свойство `computed`:

- Это явно. Так `result` будет описан именно как вычисляемый, а не как самостоятельная переменная с собственным значением
- Не нужно самостоятельно определять зависимости отслеживания и контролировать корректность списка зависимостей
- Эффективнее - вычисляемые свойства ленивые и вычисляются только, когда к их значению обращаются

2024-12-28 11:00 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-28 11:00 UTC, KiraIsmailova commented on 02-basics-2/30-calculator/CalculatorApp.js
> +    watch([firstNum, secondNum, operator], calc);
поняла, исправила

2024-12-28 11:23 UTC, ShGKme approved these changes

2024-12-28 11:23 UTC, merged